const ICONS = {
  //Onboarding
  OB1: require("./onBoarding/ob1.png"),
  OB2: require("./onBoarding/ob2.png"),
  OB3: require("./onBoarding/ob3.png"),
  logo: require("../asset/logo.png"),

  BACKSPACE: require("./icons/backspace.png"),
  TX_SENT: require("./icons/sentLight.png"),
  TX_RECEIVED: require("./icons/receivedLight.png"),
  SEND: require("./icons/bAUP.png"),
  RECEIVE: require("./icons/bADown.png"),
  PENDING: require("./icons/Pending.png"),
  COMPLETED: require("./icons/Completed.png"),
  ERROR: require("./icons/Erorr.png"),
  COPY: require("./icons/addrCopy.png"),
  LOGO_LOW: require("./icons/lowLogo.png"),
  PHRASE_COPY_BUTTON: require("./icons/phraseCopyButton.png"),
  QR_BUTTON: require("./icons/scanBtn.png"),
  SENT: require("./icons/sentLight.png"),
  RECIEVED: require("./icons/receivedLight.png"),
  BIO_SET: require("./icons/bioSet.png"),
  PIN_SET: require("./icons/pinSet.png"),
  REC_SET: require("./icons/recSet.png"),
  AUTO_HIDE: require("./icons/autohide.png"),
  SECURITY_SET: require("./icons/securitySet.png"),
  EDIT_PROFILE: require("./icons/EditProfile.png"),
  LOGOUT: require("./icons/Logout.png"),
  TICK: require("./icons/tick.png"),
  NFC: require("./icons/NFC.png"),
  QR_CODE: require("./icons/qr-code.png"),
  COPY_ADDRESS: require("./icons/copyAddress.png"),
  CONTACTS: require("./icons/contacts.png"),
  SUCCESS_BOT: require("./icons/SuccessBot.png"),
  ERROR_BOT: require("./icons/ErrorBot.png"),
  SEARCH_BOT: require("./icons/searchBot.png"),

  SUPPORT_EMAIL: require("./icons/supportEmail.png"),
  SUPPORT_CALL: require("./icons/supportCall.png"),
  //HEADER ICONS
  QR_MAIN: require("./icons/qrMain.png"),
  HEADER_BACK: require("./icons/headerLeft.png"),
  HEADER_CROSS: require("./icons/closeHeader.png"),
  //MODAL ICONS
  SUCCESS: require("./icons/Framesuccess.png"),
  MODAL_CLOSE: require("./icons/modalClose.png"),
  MODAL_ERROR: require("./icons/modalError.png"),
  //INPUT ICONS
  EYE: require("./icons/bi_eye-filleye.png"),
  EYE_OFF: require("./icons/eye-off.png"),
  EMAIL: require("./icons/Vectormessage.png"),
  LOCATION: require("./icons/GroupLocation.png"),
  COMPANY: require("./icons/VectorCompany.png"),
  NUMBER: require("./icons/GroupNumber.png"),
  CHEV_DOWN: require("./icons/chevDown.png"),
  //MENU ICONS
  CONTACT_MENU: require("./icons/contactMenu.png"),
  COPY_MENU: require("./icons/copyMenu.png"),
  NFC_MENU: require("./icons/nfcMenu.png"),
  QR_MENU: require("./icons/qrMenu.png"),
  //SETTINGS_ICONS
  RECOVERY_PRHASE: require("./icons/recSet.png"),
  CHANGE_PIN: require("./icons/pinSet.png"),
  ENABLE_BIOMETRY: require("./icons/bioSet.png"),
  SECURITY_SETTINGS: require("./icons/securitySet.png"),
  ARROW_BACK: require("./icons/arrowBack.png"),
  CONTACT_MENU_FILLED: require("./icons/contactMenuFilled.png"),
  CLIPBOARD: require("./icons/circletab.png"),
};

export { ICONS };
