import { RF, WP } from "./responsive";

export const THEME = {
  COLORS: {
    primaryBackground: "#FFFFFF",
    primaryLightBackground: "#F7F7F7",
    secondaryBackground: "#3B6BFF",
    secondaryLightBackground: "#68ACFF",
    primaryDarkBackground: "#F6F6F6",
    // secondaryDarkBackground: "#3B6BFF",
    intro1Color: "#E6F2FF",
    intro2Color: "#FFFFFF",
    intro3Color: "#E6F2FF",

    primaryGray: "#E6E6E6",
    primaryGrayLight: "#F5F5F5",
    blueLight: "#EBF4FF",
    blacklight: "#707070",
    buttonGray: "#E3E3E3",
    lightGray: "#F7F7F7",
    changeGreen: "#00C053",
    changeRed: "#ff3939",
    yellow: "#E4B40E",
    text: "#000",
    purple: "#6829E1",
    accentBlue: "#27A3E3",
    primarytext: "#68ACFF",
    secondarytext: "",
    lightBlue: "#68ACFF",
    textLight: "#928FA3",
    skyBlue: "#5A98FF",
    disabledTextLight: "#7f7e83",
    textExtraLight: "rgba(146, 143, 163, 0.4)",
    green: "#1CD983",
    blue: "#4C7BF6",
    red: "#FF0000",
    countRed: "#FD6969",
    gold: "#F89F36",
    white: "#fff",
    black: "#000",
    gradientTopColor: "#269CDD",
    gradientBottomColor: "#235DAC",
    dottedBorder: "#20FFFF",
    tabColor: "#131C3F",
    dotColor: "#5E93E3",
    biometryCircleButtonColor: "#414A5B",
    reddishBackground: "#e6d7d7",
    modalBackground: "rgba(0,0,0,0.4)",
    bitcoinColor: "#F7931A",
    etherumColor: "#2075C3",
    dashColor: "#0986D3",
    dogeCOlor: "#C3A723",
    dashRateColor: "green",
  },
  FONTS: {
    SIZE: {
      XXLARGE: RF(32),
      XXXLARGE: RF(34),
      XXXXLARGE: RF(34),
      XXXXXLARGE: RF(40),
      XLARGE: RF(24),
      LARGE: RF(20),
      MEDIUM: RF(18),
      SMALL: RF(16),
      XSMALL: RF(14),
      XXSMALL: RF(12),
      XXXSMALL: RF(10),
      XXXXSMALL: RF(8),
    },
    TYPE: {
      // LIGHT: "Lato-Light",
      // REGULAR: "Lato-Regular",
      // MEDIUM: "Lato-Bold",
      // SEMIBOLD: "Lato-Bold",
      // BOLD: "Lato-Black",
    },
  },
  MARGIN: {
    SUPERLOW: RF(2),
    VERYLOW: RF(4),
    LOW: RF(8),
    MID_LOW: RF(12),
    NORMAL: RF(16),
    HIGH: RF(24),
    VERYHIGH: RF(32),
    SUPERHIGH: RF(48),
    NOVAHIGH: RF(60),
  },
  PADDING: {
    SUPERLOW: RF(2),
    VERYLOW: RF(4),
    LOW: RF(8),
    NORMAL: RF(16),
    HIGH: RF(24),
    VERYHIGH: RF(32),
    SUPERHIGH: RF(48),
  },
  RADIUS: {
    BOX: RF(10),
    SMALLBOX: RF(5),
    OVAL: RF(24),
  },
  SIZE: {
    BUTTONWIDTH: WP(85),
  },
};
export const backgroundColorProperty = () => {
  return {
    backgroundColor: THEME.COLORS.primaryLightBackground,
  };
};

export const fontColorPropery = () => {
  return { color: THEME.COLORS.black };
};
